# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5390/trust-registry-db"
    username: "postgres"
    password: "secret"

  jpa:
    properties:
      hibernate:
        ddl-auto: create

  docker:
    compose:
      enabled: true
      file: compose.yml

logging:
  level:
    ch.admin.bit.eid: DEBUG
